config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'recipes#index'
  resources :recipes
  resources :ingredients
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
	belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	has_many :ingredients, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
	def new
		@recipe_id = params[:recipe_id]
		@ingredient = Ingredient.new
	end
	def create
		@recipe = Recipe.find(params[:ingredient][:recipe_id])
   		Ingredient.create(ingredient_params)
  	
   		redirect_to @recipe
	end

	def edit
		@ingredient = Ingredient.find(params[:id])
	end

	def show
		@recipe = Recipe.find(params[:id])
	end

	def update
	# 	@ingredient = Ingredient.find(params[:id])
	#     if @ingredient.update(ingredient_params)
	#       redirect_to ingredient_url(@ingredient)
	#     else
	#       redirect_to recipe
	#     end
	# end
		ingredient = Ingredient.find(params[:id])
	    ingredient.update(ingredient_params)

	    redirect_to recipes_url
	end
	def destroy
	    ingredient = Ingredient.find(params[:id])
	    ingredient.destroy

	   	redirect_to recipes_url
	end
	private
	def ingredient_params
	params.require(:ingredient).permit(:name, :amount, :measurement, :is_available, :recipe_id)
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	def index
		@recipes = Recipe.all
	end

	def new
		@recipe = Recipe.new  
	end

	def show
		@recipe = Recipe.find(params[:id])
	end

	def create
		@recipe = Recipe.new(recipe_params)
		if @recipe.save
			redirect_to @recipe
		else
			redirect_to new_recipe_url
		end
	end
	def edit
    	@recipe = Recipe.find(params[:id])
  	end

	def update
	   recipe = Recipe.find(params[:id])
	   recipe.update(recipe_params)

	   redirect_to recipe
	
# @recipe = Recipe.find(params[:id])
#   if @recipe.update(recipe_params)
#     new_recipe_directions = params[:new_recipe].split(",")
#     new_recipe_directions.each do |directions|
#       @recipe.directions.create(directions: directions)
#     end
#     redirect_to recipe_url(@recipe)
#   else
#     redirect_to recipes_edit_url
#   end
	end

	def destroy
	    recipe = Recipe.find(params[:id])
	    recipe.destroy
	    redirect_to recipes_url
	   # redirect_to recipes_path
	end
	private
	def recipe_params
	  params.require(:recipe).permit(:title, :img, :description, :made_it_yet, :directions)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ingredients/edit.html.erb
<div class="container">
<h2 class= "center #d50000 red accent-4">Edit Ingredients</h2>
<br>
<div class="#ffffff white">
<%= form_for @ingredient do |f|%>
<div class="center">
    <%= f.label :name, :style=>"color:black; font-size:17px;" %>
    <%= f.text_field :name%>
</div>
<div class="center">
    <%= f.label :amount, :style=>"color:black; font-size:17px;" %>
    <%= f.text_field :amount%>
</div>
<div class="center">
    <%= f.label :measurement, :style=>"color:black; font-size:17px;"%>
    <%= f.text_field :measurement%>
</div>
<div class="center">
    <button class="waves-effect waves-light #d50000 red accent-4"><%= f.label :is_available, :style=>"color:black; font-size:17px;" %></button>
    <%= f.check_box :is_available%>
</div>
<br><br>
<div class="center"><button class="waves-effect waves-light #d50000 red accent-4"><%= f.submit "Submit" %></button></div>
<br><br>
<% end %>
</div>
</div>
<br><br>
<div class="center"><button class="#d50000 red accent-4"><a href= "/" class="black-text text-darken-2">GET OUT!!!</a></button></div>
<br>

app/views/ingredients/new.html.erb
<div class="container">
<h2 class= "center #d50000 red accent-4">New Ingredient</h2>
<br>
<div class="#ffffff white">
<%= form_for @ingredient do |f| %>
<div class="center">
    <%= f.hidden_field :recipe_id, :value => params[:recipe_id] %>
</div>
<div class="center">
    <%= f.label :name, :style=>"color:black; font-size:17px;" %>
    <%= f.text_field :name %>
</div>
<div class="center">
    <%= f.label :amount, :style=>"color:black; font-size:17px;" %>
    <%= f.text_field :amount %>
</div>
<div class="center">
    <%= f.label :measurement, :style=>"color:black; font-size:17px;" %>
    <%= f.text_field :measurement %>
</div>
<div class="center">
    <button class="waves-effect waves-light #d50000 red accent-4"><%= f.label :is_available, :style=>"color:black; font-size:17px;" %></button>
    <%= f.check_box :is_available %>
</div>
<br><br>
<div class="center"><button class="waves-effect waves-light #d50000 red accent-4"><%= f.submit "Submit" %></button></div>
<br><br>
<% end %>
</div>
</div>
<br><br>
<div class="center"><button class="#d50000 red accent-4"><a href= "/" class="black-text text-darken-2">GET OUT!!!</a></button></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Itsraw</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-image: url(http://i.imgur.com/t51f3J2m.jpg)">
  	
    <%= yield %>
  </body>
</html>
<!-- sources for Gordon Ramsay pics: 
  	http://reallyusefultraininganddevelopment.ie/wp-content/uploads/2011/07/angry3_25oct07_wenn_170.jpg

	http://66.media.tumblr.com/tumblr_lqyp9fwBS61qa0fbpo1_1280.png

	http://www.vitadamamma.com/wp-content/uploads/2015/06/gordon-ramsay.jpeg

	https://pbs.twimg.com/profile_images/3550680490/c18277bddf17b9759afd7da6f38d3283_400x400.jpeg

	https://i.ytimg.com/vi/AVMtt2o2KiI/hqdefault.jpg
	http://www.ahlanlive.com/sites/default/files/images/2014/07/27/gordon.JPG

	https://i.ytimg.com/vi/UjE-cBDFphQ/hqdefault.jpg
	http://www.2004dnc.com/hellskitchen/hellskitchen_gordonramsay_2a.jpg -->

app/views/recipes/edit.html.erb
<div class="container">
<h1 class= "center #d50000 red accent-4">Edit Recipe</h1>
<br>
<div class="#ffffff white">
<%= form_for @recipe do |f| %>
  <div class="center">
   <%= f.label :title, :style=>"color:black; font-size:17px;" %>
   <%= f.text_field :title %>
 </div>
 <div class="center">
    <%= f.label :img, :style=>"color:black; font-size:17px;" %>
    <%=f.text_field :img %>
  </div>
 <div class="center">
   <%= f.label :description, :style=>"color:black; font-size:17px;" %>
   <%= f.text_area :description %>
 </div>
 <div class="center">
   <button class="waves-effect waves-light #d50000 red accent-4"><%= f.label :made_it_yet, :style=>"color:black; font-size:17px;" %></button>
   <%= f.check_box :made_it_yet %>
 </div>
 <div class="center">
    <%= f.label :directions, :style=>"color:black; font-size:17px;" %>
    <%= f.text_area :directions %>
</div>
 <div class="center"><button class="waves-effect waves-light #d50000 red accent-4"><%= f.submit "Submit"%></button></div>
<% end %>
</div>
</div>
<br><br>
<div class="center"><button class="waves-effect waves-light #d50000 red accent-4"><a href= "/" class="black-text text-darken-2">GET OUT!!!</a></button></div>
<br>

app/views/recipes/index.html.erb
<body>
<div class="container">
<h1 class="center col s12; #d50000 red accent-4">It's RAAWWW!!!!</h1>
<div class="center"><button class="#d50000 red accent-4"><a href= "/recipes/new" class="black-text text-darken-2">ADD A NEW RECIPE</a></button></div>
<br><br>
<table class="bordered #ffffff white">
  <tr>
    <th>Title</th>
    <th>Image</th>
    <th>Description</th>
    <th>Made it yet?</th>
  </tr>

  <% @recipes.each do |recipe| %>
    <tr>
      <td><button class="#d50000 red accent-4" style="width:100%"><%= link_to recipe.title, recipe, :style=>"color:black;" %></td></button>
      <td><img style='width: 100px; height 100px;' src =<%= recipe.img %> /></td>
      <td><%= recipe.description %></td>
      <td><%= recipe.made_it_yet %></td>
    </tr>
  <% end %>
</table>
</div>
</body>

app/views/recipes/new.html.erb
<div class="container">
<h1 class= "center #d50000 red accent-4">New Recipe</h1>
<br>
<div class="#ffffff white">
<%= form_for @recipe do |f| %>
  <div class="center">
    <%= f.label :title, :style=>"color:black; font-size:17px;" %>
    <%= f.text_field :title %>
  </div>
  <div class="center">
    <%= f.label :img, :style=>"color:black; font-size:17px;" %>
    <%=f.text_field :img %>
  </div>
  <div class="center">
    <%= f.label :description, :style=>"color:black; font-size:17px;" %>
    <%= f.text_area :description %>
  </div>
  <div class="center">
    <button class="waves-effect waves-light #d50000 red accent-4"><%= f.label :made_it_yet, :style=>"color:black; font-size:17px;" %>
    <%= f.check_box :made_it_yet %>
  </div>
  <div class="center">
    <%= f.label :directions, :style=>"color:black; font-size:17px;" %>
    <%= f.text_area :directions %>
</div>
  <div class="center"><button class="waves-effect waves-light #d50000 red accent-4"><%= f.submit "Submit" %></button></div>
<% end %>
</div>
</div>
<br><br>
<div class="center"><button class="#d50000 red accent-4"><a href= "/" class="black-text text-darken-2">GET OUT!!!</a></button></div>

app/views/recipes/show.html.erb
<body>
  <div class="container">
<h2 class="col s12; #d50000 red accent-4"><%= @recipe.title %></h2>
<div class = "row">
  <div class="col s6 push-s6">
  <h4 class="#d50000 red accent-4">Directions:</h4> 
  <pre style= 'white-space: pre-wrap; word-wrap: break-word; width:300px; height:600px; font-family: roboto' class="#ffffff white">
    <%= @recipe.directions %></pre>
</div>
<div class="col s6 pull-s6">
  <div class="show_image"><img style='width: 100%; height:100% margin:0; padding:0' src= <%= @recipe.img %>  /></div> 
  <h5 class="#d50000 red accent-4">Description:</h5> 
    <p class="#d50000 red accent-4"><%= @recipe.description %></p>
  <h5 class="#d50000 red accent-4">Made it Yet?</h5> 
    <p class="#d50000 red accent-4"><%= @recipe.made_it_yet %></p>
</div>
</div>
<br>
<button class="#d50000 red accent-4"><%= link_to "DONKEY!!Edit #{@recipe.title}", edit_recipe_path(@recipe), :style=>"color:black;" %></button>
<button class="#d50000 red accent-4"><%= link_to "SHUT IT DOWN!", recipe_path(@recipe), method: :delete, data: { confirm: 'Are you sure you want to delete?' }, :style=>"color:black;"%></button>
<h3 class="center col s12; #d50000 red accent-4">Ingredients</h3>
<div class="center"><button class="#d50000 red accent-4"><%= link_to "New Ingredient", new_ingredient_path(:recipe_id => @recipe.id), :style=>"color:black;"%></button></div>
<br><br>
<table class="bordered #ffffff white">
  <tr>
    <th>Name</th>
    <th>Amount</th>
    <th>Measurement</th>
    <th>Available?</th>
  </tr>

  <% @recipe.ingredients.each do |ingredient| %>
    <tr>
      <td><%= ingredient.name %></td>
      <td><%= ingredient.amount %></td>
      <td><%= ingredient.measurement %></td>
      <td><%= ingredient.is_available %></td>
       <td><% ingredient.recipe_id %></td>
      <td><button class="#d50000 red accent-4"><%= link_to "Edit", edit_ingredient_path(ingredient.id), :style=>"color:black;"%></td></button>
      <td><button class="#d50000 red accent-4"><%= link_to "Delete", ingredient_path(ingredient.id),  method: :delete, :style=>"color:black;" %></td></button>
    </tr>
  <% end %>
</table>
<br><br>
<div class="center"><button class="waves-effect waves-light #d50000 red accent-4"><a href= "/" class="black-text text-darken-2">GET OUT!!!</a></button></div>

</div>
</body>
<br><br.